server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/

spring:
  application:
    name: eureka-client
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web