server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ZhouTingZhaobiu/SpringCloudTest/
          search-paths: respo
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
