spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#          lower-case-service-id: true
      routes:
        - id: clientsss
          uri: lb://eureka-client
          predicates:
          - Path=/client/**
          filters:
          - StripPrefix=1

server:
  port: 9999

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/

feign:
  hystrix:
    enabled: true