server:
  port: 8089

spring:
  application:
    name: zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/

zuul:
  routes:
    gali:
      path: /gali/**
      serviceId: feign
    gali1:
      path: /gali1/**
      serviceId: feign1
